---
title: "Xenon"
author:
    name: "W. Kaisers"
    affiliation: "Düsseldorf"
date: "14.07.2021"
bibliography: xenon.bib
output:
    html_document:
        theme: spacelab
        toc: true
        toc_depth: 3
---

--------------------------------------------------------------------------------

<!--- --------------------------------------------------------------------- --->
# Raspberry Pi
<!--- --------------------------------------------------------------------- --->

## Network

 - Find Raspberry in network: `arp -a`
 - Pi as [WLAN access point](https://www.elektronik-kompendium.de/sites/raspberry-pi/2002171.htm)
 - [WLAN Frequencies](https://www.elektronik-kompendium.de/sites/net/1712061.htm)

--------------------------------------------------------------------------------

<!--- --------------------------------------------------------------------- --->
# Dräger devices
<!--- --------------------------------------------------------------------- --->

## Medibus protocol

 - [Evita V800 / V600](https://www.draeger.com/Library/Content/9055601_04_IfU_Evita_V800_V600_SW1_n_en.pdf)
 - [Medibus Procol Definition](https://hit.healthsystem.virginia.edu/index.cfm/_api/render/file/?fileID=DC02EE3A-17A4-77A0-3E1CF4BE2E1B9EA8&fileEXT=.pdf)
 - [Medibus for Primus](https://www.draeger.com/Products/Content/IfU_SP_Primus_MEDIBUS_for_Primus__Primus_IE__Apollo_and_Pallas_9037426.pdf)


 - Primus password: 8056
 - Evita password: 1210

--------------------------------------------------------------------------------

<!--- --------------------------------------------------------------------- --->
# RS232
<!--- --------------------------------------------------------------------- --->

In order to get access to the serial port on a linux system, it may be 
necessary to add the current user to the `dialout` group:

 - `usermod -aG dialout $USER` command (in root environment: su -)
 - Restart 
 - Monitor serial communication using `cutecom`


## Communication via USB to Serial/UART/RS232 

Status of USB adapter interface can be monitored using dmesg `dmesg | grep tty`
indicates connection and disconnection of cable:

```
[    0.201056] printk: console [tty0] enabled
[    3.999890] usb 1-1: pl2303 converter now attached to ttyUSB0
[ 5207.383172] pl2303 ttyUSB0: pl2303 converter now disconnected from ttyUSB0
[ 5636.457821] usb 1-1: pl2303 converter now attached to ttyUSB0
```

For prolific chip set, `dmesg | grep pl2303` or `dmesg | grep 1-1` provides
additional information.


## Use Minicom

 - Starting Minicom with `sudo minicom -s` prevents a program exit when error occur.
 - Set communication parameters `9600 8M1`
 - Turn on echo with  `Ctrl-a & e`
 - End session, with `Ctrl+a` followed `Ctrl+x`.

## Use Linux terminal commands

 - `echo -e "\x1b\x51\x36\x43\x0d" > /dev/ttyS0`

## Additional resources

 - [Stackexchange](https://unix.stackexchange.com/questions/117037/how-to-send-data-to-a-serial-port-and-see-any-answer)


--------------------------------------------------------------------------------

<!--- --------------------------------------------------------------------- --->
# Dräger Medibus communication standard
<!--- --------------------------------------------------------------------- --->

This description of **Medibus** data exchange bases on two documents:

 - [Medibus 6.0.0](https://hit.healthsystem.virginia.edu/index.cfm/_api/render/file/?fileID=DC02EE3A-17A4-77A0-3E1CF4BE2E1B9EA8&fileEXT=.pdf)
 - [MEDIBUS for Primus, Primus IE, Apollo and Pallas](https://www.draeger.com/Products/Content/IfU_SP_Primus_MEDIBUS_for_Primus__Primus_IE__Apollo_and_Pallas_9037426.pdf)
 

## Message structure

In general, a Medibus message can be divided into three constituents:

 - Message header: Two bytes encoding for the message type and the command code
 - An optional payload
 - Message trailer: Two bytes checksum and a terminating 0x0d (CR, carriage return)

 - First byte: Type character (ESC=0x1b  or SOH 0x01)
 - Second byte: Command code
 - Optional payload
 - Checksum
 - Terminating 0x0d (CR, carriage return)
 - Maximal allowed length of response is 3845 bytes.
 

There are two types of messages, determined by the first transmitted byte
[@MbProtDef](p.4):

 - Commands: ESC (0x1b)
 - Responses: SOH (0x01), *Start Of Header*

The second byte encodes a command code

 - Commands: The command type (for example ICC: 0.51)
 - Responses: The echo of the command responded to.
 
There are three command types:

 - Control commands (p. 8)
 - Data request commands (p. 8)
 - Miscellaneous commands

Miscellaneous commands:

 - Time changed (0x49)
 - Configure data response (0x4A)

##  AsciiHex Format

Allowed characters:

 - Printable ASCII 0x20 (32) - 0x7F (127)
 - Control characters defined in the **Medibus** standard.
 
Ascii encoding:

 - Space: 0x20 (32)
 - Numeric (0-9): 0x30 (48) - 0x39 (57)
 - Upper case (A-Z): 0x41 (65) - 0x5A (90)
 - Lower case (a-z): 0x61 (97) - 0x7A (122)


## Standard messages

### Commands

MSG     ASCII Hex               hex
------  ----------------------- ---------------------------------
ICC     1BH 51H 36H 43H 0DH     `[ 0x1b, 0x51, 0x36, 0x43, 0x0d ]`
ID      1BH 52H 36H 44H 0DH     `[ 0x1b, 0x52, 0x36, 0x44, 0x0d ]`
NOP     1BH 30H 34H 42H 0DH     `[ 0x1b, 0x30, 0x34, 0x42, 0x0d ]`
STOP    1BH 55H 37H 30H 0DH     `[ 0x1b, 0x55, 0x37, 0x30, 0x0d ]`

### Responses

MSG     ASCII Hex               hex
------  ----------------------- ---------------------------------
ICC     01H 51H 35H 32H 0DH     `[ 0x01, 0x51, 0x35, 0x32, 0x0d ]`
ID      01H 52H 56H 33H 0DH     `[ 0x01, 0x52, 0x35, 0x33, 0x0d ]`
NAK     01H 15H 31H 36H 0DH     `[ 0x01, 0x15, 0x31, 0x36, 0x0d ]`


--------------------------------------------------------------------------------

<!--- --------------------------------------------------------------------- --->
## Message flow
<!--- --------------------------------------------------------------------- --->

<!--- --------------------------------------------------------------------- --->
## General rules
<!--- --------------------------------------------------------------------- --->

Medibus commands [@MbProtDef] (p.12):

 - Any new command must not be sent before the response to a previous command has
    been received.
 - New commands can be submitted 10 seconds after the last command when no
    answers have been received.
 - A complete response must be sent within 10 sec after receiving a command.

<!--- --------------------------------------------------------------------- --->
## Initialize communication
<!--- --------------------------------------------------------------------- --->
 - For initialization, the ICC command
 - ICC commands always require a response [@MbProtDef] (p.12)

<!--- --------------------------------------------------------------------- --->
## Stop communication
<!--- --------------------------------------------------------------------- --->
 - Send **STOP** command
 - Check command echo,
 

### Timeout

 - The communication is stopped, when no message is sent (or received) for
    more than 3 seconds.
 - A `NOP` – command has to be sent within 2-second-intervals to keep the 
    communication alive.
        
 - It will suffice if the PC sends an NOP response to the Dräger medical device
        within approx. 1 second. 
 - It is better when PC sends an NOP command itself.


 - Time changed (0x49)
 - Configure data response (0x4A)


## Responses

 - SOH (0x01) Start of header
 - Command echo
 - Response
 - Checksum
 - Terminating 0x0D
 
### Responses to Control and unknown commands

 - SOH 
 - Command Echo
 - No payload (data)
 - Checksum, CR

<!--- --------------------------------------------------------------------- --->
## Payload
<!--- --------------------------------------------------------------------- --->
### Responses to data request commands

Requested data is sent in segments of 6 bytes length:

 - Two bytes **data code** identifying the parameter
 - Four bytes **data** containing the current value

Empty positions and leading zeros must be transmitted as space (0x20).


--------------------------------------------------------------------------------

<!--- --------------------------------------------------------------------- --->
# Logging
<!--- --------------------------------------------------------------------- --->

Xenon uses [npm winston](https://www.npmjs.com/package/winston) for logging.
The location of the logfiles is defined the configuration:

 - Path: `/config/general`
 - Property: `logger.logdir`


## Status logging

Status logging is intended to save changes of settings, defined in 
*Text-Message-Response* to a file.

The status logger takes an object containing four properties:

 - code: Textual representation of numeric value
 - text: Text content as received from message
 - begin: TimePoint (id, time)
 - end: TimePoint
 
 Status changes will be logged, by `ParameterMap` upon call of
 
  - `expireElements`
  - `exprieAll`
  
--------------------------------------------------------------------------------

<!--- --------------------------------------------------------------------- --->
# Controller
<!--- --------------------------------------------------------------------- --->

There are four controllers located in the `/controller` directory.


## PortController

The *PortController* derives from `Stream.readable` and contains
an instance of *SerialPort*.

## StatusController

The *StatusController* (/controller/statusController) manages the communication
status of the Port and the Medibus protocol.
The status is one of five levels:

| Value   | Level         | Label           |
|---------|---------------|-----------------|
| 0       | Port          | Closed          |
| 1       | Bus           | Inactive        |
| 2       | Bus           | Listen          |
| 3       | Bus           | Stopping        |
| 4       | Bus           | Initializing    |
| 5       | Com           | Protocol        |

Via emission of client notifications, the initialization and 
shutdown procedures of Medibus protocol are coordinated.

## ProtcolController

The ProtocolController on the Medibus Protocol level using the
`CommandTimeout` class:

 - initCom: Sends an `ICC` response upon receiving an ICC command and 
  set StatusController to `initializing` status
 - receiveMessage:
 - sendCommand: Creates and triggers a `CommandTimeout`
 - shutdown: Closes PortController
 - stop: Initiates regular Protocol shutdown by sending a `STOP` command
    and sets StatusController to `inactive` status


## MessageController

--------------------------------------------------------------------------------

<!--- --------------------------------------------------------------------- --->
# Event Loop
<!--- --------------------------------------------------------------------- --->

The *EventLoop* (/bus/eventLoop) defines the reaction-chain for incoming
RS-232 messages.
The event loop classes are derived from *Stream.transform*.
The processing order is

 - *Interrupt*: 
 - *MessageDelimiter* detects the end of a Medibus-Message and passes
    related data chunks to the next instance
 - *MessageParser* constructs *Message* objects from the incoming chunks
 - *React* defines the type of reaction:
  - Eventually reply to incoming commands (especially: ICC, Device-Id)
  - Receive replies (Data, STOP)
  

## Launch of communication

 - **Open Port** via portController.open
 - The portController sets Status to `listen`
 - Upon incoming ICC command, eventLoop.React calls protocolController.initCom
 - protocolController.initCom
    - Sends ICC reply
    - ProtocolController sets Status to `Initialising`
    - Sets Episode UUID via `initEpisodeUuid`    
 -  Upon Status.Initialising, MessageController does:
    - Set status to `Protocol`
    - Fill Action schedule (initial messages + message cycle)
    - Executes doNextAction which triggers transmission of first command.

## Shutdown of communication

 - Set Status to stopping.
 - NextMessage calls ProtocolController.stop() which sends STOP command
 - Reply is caught by EventLoop React which calls ProtocolController.shutdown
 - Shutdown closes port and clears StatusController episode UUID.


--------------------------------------------------------------------------------

<!--- --------------------------------------------------------------------- --->
# Data Queries
<!--- --------------------------------------------------------------------- --->

## Querying of data using Command objects

Medibus Commands are represented by *Message* objects, defined in 
`model/medibus/commands`.
*Command* messages are stored inside of *Action* objects.
See definition of query command messages [@MbProtDef] (p.8).
*Action* objects coordinate the sending of commands and the initiation of the
further data processing.
An *Action* object contains

 - a *Message* object which will be send (via *ProtocollController*) upon request
 - a Callback defining the further processing of received data.

## Scheduled query of data

The data-query Cycle is implemented in the **MessageController** (/controller/messageController).
The *MessageController* keeps an array of *Action* objects.
These *Action*s are executed one after another.

During construction, the *MessageController* first loads the initial commands

 - Request Device Identification `52H`
 - Request current Date and Time `28H`

together with a first cycle of data query commands.
One **Cycle** contains a complete set of all Data query commands which are
regularly queried:

 - Request current measured Data (Codepage 1) `24H`
 - Request current low Alarm Limits (Codepage 1) `25H`
 - Request current high Alarm Limits (Codepage 1) `26H`
 - Request current Alarms (Codepage 1) `27H`
 - Request current Alarms (Codepage 2) `2EH`
 - Request current Text Messages `2AH`

### Initialization

When the *StatusController* signals entering of `initializing` status,
the *MessageController* loads the intial set of commands together with
the first cycle and finally calls `doNextAction` for the first time.

All subsequent calls to `doNextAction` are done by *NextMessage* (event-loop).

### Query schedule

When the *MessageController* schedule array is empty, the next call to
`doNextAction` triggers

 - Reporting of the complete dataset to attached clients via *Monitor* (/monitor/monitor)
 - Push dataset to *DataCache* (/model/data/cache)


## Reporting via monitor


--------------------------------------------------------------------------------

<!--- --------------------------------------------------------------------- --->
# Parameters
<!--- --------------------------------------------------------------------- --->

## Settings

Device settings are queried using the *Request Current Device Settings* command
(29H) [@MbProtDef] (p.17).
The response consists of segments with a size of 7 bytes:

 - Two bytes *setting code*
 - Five bytes *setting*

The codes for settings ar described in [@MbPrimus] (p.13):

Code      Device Setting                 Unit      Format
------    ---------------------------    ------    ----------
01H       O2                             %         _XXX_
04H       Insp. Tidalvolume              L         X.XXX
05H       Inspiratory time               sec       _XX.X
0AH       Frequency                      1/min     XXX.X
0CH       Intermittend PEEP              mbar     _XX.X
12H       Pressure Support Pressure ΔPPS mbar     ___XX
13H       Max. insp. Airway Pressurem    bar      XXX.X
27H       Insp. Pause/insp. Time         %        __XXX
29H       Flow Trigger                   L/min    _XX.X
2EH       Slope time (Ramp)              sec      _XX.X
2FH       Freshgas Flow                  mL/min   XXXXX
42H       Minimal Frequency              1/min    XXX.X
45H       Inspiratory pressure           mbar     ___XX
4AH       Age                            a        __XXX
4BH       Weight                         kg       __XXX



## Text Message response
See Medibus for Primus [@MbPrimus] (p.34) and additionally [@MbxProfDef] (p.109).
A *Text Message Response* (TMR) [@MbProtDef] (p.18) contains all current text messages.
The response is divided into variable amounts of text-segments.
Each text-segment consists of

 - Text code: Two byte ascii-hex
 - Length: One byte (0-32)
 - Text

The related classes are

 - `TextMessageResponse`
 - `TextSegment`.

The obtained data is stored in an Array of Segment data-objects.
Each data-object is made up of the following fields:

 - `id`: Message-ID
 - `time`: Message time
 - `code`: String representation of text-code: `[ 0x32, 0x33 ] -> '23'`
 - `text`: Transmitted Text message
 
After reading the text segments out of the message, the values are copied
into a default parameter object.

### Text Messages

Code  Text Message[@MbPrimus]
----- --------------------------------------------
01H   Ventilationmode IPPV
06H   Ventilationmode SIMV
1EH   Ventilator is in Standby-Mode
22H   Selected CO2 Unit is mmHg
23H   Selected CO2 Unit is kPa
24H   Selected CO2 Unit is %
25H   Halothane detected
26H   Enflurane detected
27H   Isoflurane detected
28H   Desflurane detected
29H   Sevoflurane detected
2AH   No Anaesthesia Gas detected
2BH   Ventilationmode man./spont.
2CH   Selected Language
34H   Ventilationmode PCV
36H   Ventilationmode FRESH GAS EXTERNAL
37H   Selected Carrier Gas is Air
38H   Selected Carrier Gas is N2O
4AH   2nd Agent Halothane detected
4BH   2nd Agent Enflurane detected
4CH   2nd Agent Isoflurane detected
4DH   2nd Agent Desflurane detected
4EH   2nd Agent Sevoflurane detected
4FH   No 2nd Anesthesia Gas detected
53H   Device is performing leakage test
54H   Device is in Standby-Mode
56H   Selected Agent Unit is kPa
57H   Selected Agent Unit is %
58H   HLM Mode active
59H   Volume controlled Ventilation Mode
5AH   Pressure controlled Ventilation Mode
5BH   Pressure Support Mode
5CH   Pressure Support added to intermittent Ventilation Mode
5DH   Synchronized intermittent Ventilation
4EH   AutoFlow added to Volume Mode

Code  Text Message[@MbxProfDef] (p.109-127)
----- --------------------------------------------
01H   Mode VC-CMV
02H   Mode VC-AC
04H   Mode SPN-CPAP
06H   Mode VC-SIMV
0CH   Mode VC-MMV
0DH   Mode PC-MMV
0EH   Mode PC-BIPAP
18H   Mode PC-SIMV
1AH   Mode PC-APRV
1BH   Mode PC-HFO
47H   Mode PC-AC
6AH   Mode PC-CMV
6BH   Mode O2 therapy

1EH   Ventilator is in standby mode

20H   Device is in adult mode
21H   Device is in neonatal mode

11H   Automatic apnea ventilation active
12H   Device in PRODUCT TEST mode


#### Derived parameters

The text messages often describe entities where different modes are
represented by different message types.
There are for example multiple messages describing ventilation mode or 
detected anesthesia gas or 2nd agent.
Derivation of parameters tries to condense out the described entities
together with their modes.

##### Derived device parameters


Code                Parameter           Description             Modes
----------------    -----------------   --------------------    ----------------
2CH                 `language`          Language                D: deutsch, GB: english, ...
22H, 23H, 24H       `co2unit`           CO<sub>2</sub>-Unit     mmHg, kPa, %
56H, 57H            `agentunit`         Agent-Unit              kPa, %
58H, 1EH, 53H       `devicemode`        Device-mode             HLM, Standby, Leaktest
37H, 38H            `carrier`           Carrier-gas             Air, N<sub>2</sub>O



### Ventilation parameters

+---------------+---------------+---------------------------------------------------------+
| Code          | Parameter     | Description                                             |
+:==============+:==============+:========================================================+
|               | `inhal`       | Anaesthesia gas                                         |
+---------------+---------------+---------------------------------------------------------+
|               | `secInhal`    | 2nd Anaesthesia gas                                     |
+---------------+---------------+---------------------------------------------------------+
|               | `carrier`     | Carrier gas                                             |
+---------------+---------------+---------------------------------------------------------+
|               | `ventmode`    | Ventilation mode                                        |
+---------------+---------------+---------------------------------------------------------+
|               | `sync`        | Synchronized vent                                       |
+---------------+---------------+---------------------------------------------------------+
|               | `psvadd`      | Pressure support added to intermittent Ventilation Mode |
+---------------+---------------+---------------------------------------------------------+
|               | `autoflow`    | Autoflow added to Volume mode                           |
+---------------+---------------+---------------------------------------------------------+
|               | `airway`      | Airway device configured                                |
+---------------+---------------+---------------------------------------------------------+



### ParameterMap

The ParameterMap class is designed to serve as repository for past status
parameters.
A TMR always contains a complete list of *current* status parameter.
In order to get the beginning and end of a status, the current status needs to
be checked against past TMR.
The *ParameterMap* thus contains a *Map* of *ParameterElements* (identified by
the message code).
Each time, a TMR is processed, all *TextSegments* are checked against the
Map and either inserted or updated (upsert).
After processing all TextSegments, the expired parameters (identified by an
outdated message-id) are shifted into an (*expired*) array.

The data is accessible via REST at

 - `host:/data/text/current`
 - `host:/data/text/expired`



--------------------------------------------------------------------------------

<!--- --------------------------------------------------------------------- --->
# Ontologies
<!--- --------------------------------------------------------------------- --->

## Parameter

ID    Label                                             Reference
---   ----------------------------------------------    -------------------------
1     Measured Data, Low and High Alarm Limits          Primus [@MbPrimus] (p. 8)
2     Device Settings                                   Primus [@MbPrimus] (p.13)
3     Text Messages                                     Primus [@MbPrimus] (p.34)



## Snomed-CT

 - [Snomed-CT via Bioontology](https://bioportal.bioontology.org/ontologies/SNOMEDCT)
 - [Cnomed CT Editorial Guide](https://confluence.ihtsdotools.org/display/DOCEG/SNOMED+CT+Editorial+Guide)
 - [IHTSDO tools](https://browser.ihtsdotools.org/)
 - [EBI homepage](https://www.ebi.ac.uk/ols/ontologies/snomed)

SCTID       Name
----------  --------------------------------------------------------------------
426854004   High flow oxygen nasal cannula
371907003   Oxygen administration by nasal cannula
243142003   Dual pressure spontaneous ventilation support
250854009   Positive end expiratory pressure
286812008   Pressure controlled ventilation


### Snomed-CT for observable entities

  * 138875005 Snomed CT Concept 
    * 363787002  Observable entity

SCTID         Name
----------    ------------------------------------------------------------------
250854009     Positive end expiratory pressure




### Snomed-CT for Standard ventilation modes

  * 71388002  Procedure 
    * 243120004 Regimes and therapies


SCTID         Name
----------    ---------------------------------------------------------------------------   ---
1222606000    Continuous Mandatory Ventilation (CMV)                                        regime/therapy
1186749003    Continuous mandatory ventilation volume-control inflation-type (CMV-VC)
1187023008    Continuous mandatory ventilation pressure-control inflation-type
1197612007    Intermittent mandatory ventilation (IMV)
1186622005    Synchronized IMV - pressure-control pressure-support inflation
1186621003    Synchronized IMV - volume control pressure-support inflation
1186733000    Continuous spontaneous ventilation (CSV) with effort support
1186731003    Continuous spontaneous ventilation with pressure support
1186732005    Continuous spontaneous ventilation with volume targeted pressure-support

### Snomed-CT for Dräger defined modes

Dräger        SCTID         Name
----------    ----------    ----------------------------------------------------
PC-BIPAP      243142003     Dual pressure spontaneous ventilation support
MMV           1186620002    Minimum minute volume ventilation
APRV          243143008     Airway pressure release ventilation
CPAP          47545007      Continuous positive airway pressure ventilation treatment

PC-AC
VC-MMC


--------------------------------------------------------------------------------

<!--- --------------------------------------------------------------------- --->
# References
<!--- --------------------------------------------------------------------- --->