---
title: "Ontologies"
author:
    name: "W. Kaisers"
    affiliation: "Düsseldorf"
date: "18.02.2023"
bibliography: ontology.bib
output:
    html_document:
        theme: spacelab
        toc: true
        toc_depth: 3
---
--------------------------------------------------------------------------------

<!--- --------------------------------------------------------------------- --->
# Parameters
<!--- --------------------------------------------------------------------- --->

## FHIR Codes

In FHIR, 
[Ventilation Observations](https://build.fhir.org/ig/HL7/fhir-saner/ValueSet-VentilatorObservations.html)
are contained in ValueSet `10.97.1`.
All codes are derived from [LOINC](http://loinc.org)

Code      Display
-------   -------------------------------------------------------------------------
19835-8   Breath rate setting Ventilator synchronized intermittent mandatory
19994-3   Oxygen/Total gas setting [Volume Fraction] Ventilator
20077-4   Positive end expiratory pressure setting Ventilator
20079-0   Pressure support setting Ventilator
20103-8   Tidal volume expired/Plateau pressure --post 1.5-2.0 seconds inspiratory hold on ventilator
20112-9   Tidal volume setting Ventilator
20115-2   Tidal volume.spontaneous/Body weight [Volume/mass] --on ventilator
33438-3   Breath rate mechanical --on ventilator
57655-3   Tidal volume.exhaled maximum setting Ventilator alarm
76530-5   Mean pressure Respiratory system airway --on ventilator
19839-0   Breath rate spontaneous --on ventilator

## LOINC Codes

Code          Display
--------      -------------------------------------------------------------------------
88034-4       Ventilator settings Document
19996-8       FIO2 on vent
19834-1       Breath rate setting Ventilator
74201-5       Days on ventilator
20124-4       [Ventilation mode Ventilator](https://loinc.org/20124-4/)

Code          Display
--------      -------------------------------------------------------------------------
LP7706-7      Ventilator
LA19016-7     Manual
LA12671-6     Assisted ventilation
LA29246-8     Controlled ventilation
LL5054-3      Manual|Assist|Ctrl|Assist-Ctrl|MMV|Other

# Snomed-CT

 - [Bioontology](https://bioportal.bioontology.org/ontologies/SNOMEDCT)

## International Patient Summary

 - [International Patient Summary](https://www.snomed.org/snomed-ct/Other-SNOMED-products/international-patient-summary-terminology)
 - [IPS Viewer](https://www.ipsviewer.com/)


Contains:

 - Header
 - Patient
 - Allergies
 - Active Problems
 - Current medications
 - Observations


## Observation hierarchy

[Respiratory therapy](http://purl.bioontology.org/ontology/SNOMEDCT/53950000)
>
[Assisted breathing](http://purl.bioontology.org/ontology/SNOMEDCT/266700009)
>
[Artificial respiration](http://purl.bioontology.org/ontology/SNOMEDCT/40617009)


### Devices 

* [Clinical equipment](http://purl.bioontology.org/ontology/SNOMEDCT/272181003)
  * [Pulseoxymeter](http://purl.bioontology.org/ontology/SNOMEDCT/448703006)
  * [Carbon dioxide analyzer](http://purl.bioontology.org/ontology/SNOMEDCT/33388001)
 
[Snomed CT](http://purl.bioontology.org/ontology/SNOMEDCT/243141005)


## Cochrane Linked Data

 - Procedure [Dual Pressure Spontaneous Ventilation](https://data.cochrane.org/concepts/r4hp5zhbl4f2) = BIPAP


--------------------------------------------------------------------------------

<!--- --------------------------------------------------------------------- --->
# References
<!--- --------------------------------------------------------------------- --->