---
title: "Ontologies"
author:
    name: "W. Kaisers"
    affiliation: "Düsseldorf"
date: "18.02.2023"
bibliography: ontology.bib
output:
    html_document:
        theme: spacelab
        toc: true
        toc_depth: 3
---
--------------------------------------------------------------------------------

<!--- --------------------------------------------------------------------- --->
# Organisationen
<!--- --------------------------------------------------------------------- --->

 - [SITiG](https://www.sitig.de/mitglieder.html) (Spitzenverband IT-Standards im Gesundheitswesen)
 - [PCHAlliance](https://www.pchalliance.org/) (Personal Connected Health Alliance)
 - Bundesverband Gesundheits-IT [bvitg e. V.](https://www.bvitg.de/)

<!--- --------------------------------------------------------------------- --->
# Medizininformatik Initiative (MII)
<!--- --------------------------------------------------------------------- --->

See [MII Kerndatensatz](https://www.medizininformatik-initiative.de/de/der-kerndatensatz-der-medizininformatik-initiative):

 - [Draft 2017](https://www.medizininformatik-initiative.de/sites/default/files/inline-files/MII_04_Kerndatensatz_1-0.pdf)
 - [KDS-Governance 2021](https://www.medizininformatik-initiative.de/sites/default/files/2021-10/MII_KDS-Governance_3.0.pdf)
 - [GitHub](https://github.com/medizininformatik-initiative)
 - [MII Jahresversammlung 2021](https://www.medizininformatik-initiative.de/de/jahresversammlung2021)
 - [Medizininformatik Initiative der Kerndatensatz](https://www.medizininformatik-initiative.de/de/der-kerndatensatz-der-medizininformatik-initiative)
 - [MII Modul ICU 2022](https://www.medizininformatik-initiative.de/Kerndatensatz/Modul_Intensivmedizin/IGMIIKDSModulICU.html)
 - [MII Modul ICU Terminologien](https://www.medizininformatik-initiative.de/Kerndatensatz/Modul_Intensivmedizin/Terminologien.html)
 - [Art-Decor](https://art-decor.org/art-decor/decor-datasets--mide-): Quite rudimentary
 - [Simplifier](https://simplifier.net/)



Laut *EU Recommendation on European Electronic Health Record exchange format* [2019/243](https://eur-lex.europa.eu/eli/reco/2019/243/oj) soll die
Ausgangsbasis für ein europäisches Ausgangsformat für elektronische 
Patientenakten folgende Bestandteile enthalten:

 - Patientenkurzakte (Patient summary)
 - elektronische Verschreibung („ePrescription“)/elektronische Verabreichung („eDispensation“)
 - Laborbefunde (Laboratory results)
 - Medizinische Bildgebung und ärztliche Berichte (Medical imaging and reports)
 - Krankenhaus-Entlassungsberichte (Hospital discharge reports)

## Cocir

[Cocir](https://www.cocir.org/index.html) is the European Trade Association 
representing the medical imaging, radiotherapy, health ICT and electromedical
industries.
Recommendations:

1. Consider API standards and profiles
2. Apply a consistent and proven end-to-end strategy
3. Apply the COCIR ’Six steps’

 
## Medcom

[Medcom](https://medcom.dk/medcom-in-english/) (The Danish Health Data Network)
develops, tests and certifies (and help implement) digital standards that enable
systems in the healthcare sector to exchange relevant data in a secure way.

<!--- --------------------------------------------------------------------- --->
# Parameters
<!--- --------------------------------------------------------------------- --->

## FHIR Codes

In FHIR, 
[Ventilation Observations](https://build.fhir.org/ig/HL7/fhir-saner/ValueSet-VentilatorObservations.html)
are contained in ValueSet `10.97.1`.
All codes are derived from [LOINC](http://loinc.org)

Loinc     Display
-------   -------------------------------------------------------------------------
8302-2    Body height
29463-7   Body weight
50064-5   Ideal body weight
9279-1    Respiratory Rate


Loinc     Display
-------   -------------------------------------------------------------------------
19835-8   Breath rate setting Ventilator synchronized intermittent mandatory
19994-3   Oxygen/Total gas setting [Volume Fraction] Ventilator
20077-4   Positive end expiratory pressure setting Ventilator
20079-0   Pressure support setting Ventilator
8741-1    Left ventricular Cardiac output    
20103-8   Tidal volume expired/Plateau pressure --post 1.5-2.0 seconds inspiratory hold on ventilator
20112-9   Tidal volume setting Ventilator
20115-2   Tidal volume.spontaneous/Body weight [Volume/mass] --on ventilator
76009-0   Inspired minute Volume during Mechanical ventilation
33438-3   Breath rate mechanical --on ventilator
57655-3   Tidal volume.exhaled maximum setting Ventilator alarm
76530-5   Mean pressure Respiratory system airway --on ventilator
19839-0   Breath rate spontaneous --on ventilator
50984-4   Horowitz index in Arterial blood

## LOINC Codes

Loinc     Display
--------  --------------------------------------------------------------------------
88034-4   Ventilator settings Document
19996-8   FIO2 on vent
19834-1   Breath rate setting Ventilator
74201-5   Days on ventilator
75162-8   Biphasic positive airway pressure (BIPAP) activity Ventilator
76275-7   Inspiratory flow setting Ventilator
20124-4   [Ventilation mode Ventilator](https://loinc.org/20124-4/)

Loinc         Display
--------      -------------------------------------------------------------------------
LP7706-7      Ventilator
LA19016-7     Manual
LA12671-6     Assisted ventilation
LA29246-8     Controlled ventilation
LL5054-3      Manual|Assist|Ctrl|Assist-Ctrl|MMV|Other

# Snomed-CT

 - [Bioontology](https://bioportal.bioontology.org/ontologies/SNOMEDCT): TreeView browsing portal
 - [Community Content Browser](https://community-browser.ihtsdotools.org/?): Includes a german translation
 - [Bfarm](https://www.bfarm.de/DE/Kodiersysteme/Terminologien/SNOMED-CT/_node.html)
 - [Confluence](https://confluence.ihtsdotools.org/display/DOCSQLPG/A.1+Download+the+SNOMED+CT+Example+Database+Package)
 - [Logical Model](https://confluence.ihtsdotools.org/pages/viewpage.action?pageId=61154005)
 - [Starter guide DE](https://confluence.ihtsdotools.org/display/DOCSTARTDE/)
 - [Document library](https://confluence.ihtsdotools.org/display/DOC)
 - [Document library](https://confluence.ihtsdotools.org/display/DOC)
 - [Starter guide](https://snomed.org/sg)
 - [Snomed in action](https://www.snomed.org/snomed-in-action?lang=de)
 - [Snowstorm](https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/concepts/225796000&sa=D&source=editors&ust=1678028279118629&usg=AOvVaw0ti013dJmEFiY4kn_kaqbl)
 - [Download Database](https://confluence.ihtsdotools.org/display/DOCSQLPG/A.1+Download+the+SNOMED+CT+Example+Database+Package)
 
## Snomed-CT Structures

  * Content components
    * Concepts
    * Descriptions
    * Relationships
  * Localization mechanisms
  * Concept model
  * Expression model

A concept has

  * Unique numeric identifier (&leq; 18 digits)
  * &geq; 1 Fully specified name (FSN)
  * &geq; 1 Synonym (Syn). A synonym can be synonym of multiple concepts
  * A preferred term: The default display name


Each concept is associated with several descriptions.
Each description includes

  * An unique identifier
  * Version data
  * The identifier of the associated concept
  * The human readable term
  
Concepts contain a set of **relationships**.
Each relationship includes

  * A unique identifier
  * Version data
  * A source concept
  * **is_a**: Subtype (e.g. Procedure): Maybe multiple inheritance (Graph contains cycles)
  * **has_a**: Has an attribute (e.g. procedure site)
  
Attribute relationships. Examples

  * Procedure-site
  * Method


## International Patient Summary

 - [International Patient Summary](https://www.snomed.org/snomed-ct/Other-SNOMED-products/international-patient-summary-terminology)
 - [IPS Viewer](https://www.ipsviewer.com/)

Contains:

 - Header
 - Patient
 - Allergies
 - Active Problems
 - Current medications
 - Observations


## Procedure (71388002)

  * Procedure on body system
    * Procedure on respiratory system (118669005)

## Observation hierarchy

[Respiratory therapy](http://purl.bioontology.org/ontology/SNOMEDCT/53950000)
>
[Assisted breathing](http://purl.bioontology.org/ontology/SNOMEDCT/266700009)
>
[Artificial respiration](http://purl.bioontology.org/ontology/SNOMEDCT/40617009)


### Devices 

* [Clinical equipment](http://purl.bioontology.org/ontology/SNOMEDCT/272181003)
  * [Pulseoxymeter](http://purl.bioontology.org/ontology/SNOMEDCT/448703006)
  * [Carbon dioxide analyzer](http://purl.bioontology.org/ontology/SNOMEDCT/33388001)
 
 - [Snomed CT](http://purl.bioontology.org/ontology/SNOMEDCT/243141005)
 - [IHTSDO tools](https://browser.ihtsdotools.org/)
 - [Find-A-Code](https://www.findacode.com/snomed/)
 - [Medizininformatik](https://www.medizininformatik-initiative.de/Kerndatensatz/Modul_Intensivmedizin/Terminologien.html)


SCTID       Name
----------  --------------------------------------------------------------------
260787004   Physical object (physical object)

### Vital signs

SCTID       Name
----------  --------------------------------------------------------------------
424144002   Current chronological age (observable entity) 
1153637007  Body height (observable entity)
27113001    Body weight (observable entity)
170804003   Ideal body weight (observable entity)
86290005    Respiratory rate (observable entity)

### Ventilation

SCTID       Name
----------  --------------------------------------------------------------------
426854004   High flow oxygen nasal cannula
371907003   Oxygen administration by nasal cannula
243142003   Dual pressure spontaneous ventilation support
250854009   Positive end expiratory pressure
286812008   Pressure controlled ventilation

### Intensive care related ID's

 - [Intensiv](https://www.medizininformatik-initiative.de/Kerndatensatz/Modul_Intensivmedizin/BeschreibungModul.html)

SCTID       entity
----------  --------------------------------------------------------------------
386534000   Arterial blood pressure (observable entity)
271649006   Systolic blood pressure (observable entity)
271650006   Diastolic blood pressure (observable entity)
78564009    Heart rate measured at systemic artery (observable entity)
364075005   Heart rate (observable entity)
82799009    Cardiac output (observable entity)
103228002   Hemoglobin saturation with oxygen (observable entity)
442476006   Arterial oxygen saturation (observable entity)
103228002   Hemoglobin saturation with oxygen (observable entity)
442349007   Venous oxygen saturation (observable entity)
713194001   Central venous oxygenation saturation (observable entity)
442734002   Mixed venous oxygen saturation (observable entity)
250790007   End tidal carbon dioxide tension (observable entity)
397802005   Minute ventilation (finding)
250875001   Ventilator delivered minute volume (observable entity)
86290005    Respiratory rate (observable entity)
250774007   Inspired oxygen concentration (observable entity)
250775008   Expired oxygen concentration (observable entity)
250778005   End tidal oxygen concentration (observable entity)
425421000   Expired isoflurane concentration (observable entity)
427452000   End tidal isoflurane concentration (observable entity)
427210008   Expired sevoflurane concentration (observable entity) 
425724007   Inspired sevoflurane concentration (observable entity)
427597006   End tidal sevoflurane concentration (observable entity)
426988006   End tidal desflurane concentration (observable entity)
425621006   Expired desflurane concentration (observable entity)

SCTID       physical object
----------  --------------------------------------------------------------------
19923001    Catheter, device (physical object)
462514007   Arterial blood pressure catheter (physical object)


SCTID       regime/therapy
----------  --------------------------------------------------------------------
17146006    Arterial pressure monitoring, non-invasive method (regime/therapy)


## Cochrane Linked Data

 - Procedure [Dual Pressure Spontaneous Ventilation](https://data.cochrane.org/concepts/r4hp5zhbl4f2) = BIPAP





--------------------------------------------------------------------------------

<!--- --------------------------------------------------------------------- --->
# References
<!--- --------------------------------------------------------------------- --->